# Nombre del flujo de trabajo que aparecerá en la pestaña "Actions" de GitHub
name: Deploy React Resume to GitHub Pages

# Define cuándo se debe ejecutar este flujo de trabajo
on:
  # Se ejecuta cuando haces un push a la rama 'main'
  push:
    branches:
      - main
  # Permite ejecutar este flujo de trabajo manualmente desde la pestaña Actions
  workflow_dispatch:

# Permisos necesarios para que el job pueda desplegar en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Define los trabajos (jobs) que se ejecutarán
jobs:
  # Un único job llamado 'build-and-deploy'
  build-and-deploy:
    # El tipo de máquina virtual en la que se ejecutará
    runs-on: ubuntu-latest
    steps:
      # 1. Clona tu repositorio en la máquina virtual
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configura el entorno de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Puedes usar la versión de Node que prefieras
          cache: 'npm'

      # 3. Instala las dependencias del proyecto
      - name: Install dependencies
        run: npm install

      # 4. Construye la aplicación para producción
      # El resultado se guardará en la carpeta 'dist' por defecto en proyectos con Vite
      - name: Build
        run: npm run build

      # 5. Sube los artefactos de la construcción para el despliegue
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Asegúrate de que esta es la carpeta de salida de tu build

      # 6. Despliega los artefactos en GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
